language: php

php:
  - '5.6'
  - '7.0'

install:
  - composer install

script:
  - composer test

cache:
  directories:
    - vendor
    - $HOME/.composer

notifications:
  email:
    on_success: never
